# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
a = np.random.random((3,3,3))
print(a)

[[[0.95423834 0.09532952 0.05744096]
  [0.15162862 0.79701274 0.55031061]
  [0.22400328 0.63340594 0.96002342]]

 [[0.97563238 0.62361781 0.9406173 ]
  [0.82476371 0.43579501 0.14804848]
  [0.08769496 0.08911945 0.31125267]]

 [[0.11385063 0.0199995  0.78256286]
  [0.59610462 0.92808987 0.14212088]
  [0.47624989 0.46499595 0.87802856]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [11]:
a = np.diag([1, 2, 3, 4, 5],k=-1)
print(a[:5])

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
a = np.ones((3,3))
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [12]:
a = np.random.random((5,5))
print(a)
amax, amin = a.max(), a.min()
print("After Normalization")
a = (a - amin)/(amax - amin)
print(a)

[[0.87353278 0.77187943 0.06030979 0.1634386  0.01671604]
 [0.59519548 0.91242728 0.15904215 0.40343553 0.52869957]
 [0.85098466 0.41339149 0.36117116 0.308488   0.50786071]
 [0.88811361 0.89490722 0.56550785 0.59827857 0.84093204]
 [0.37372454 0.47693608 0.11155003 0.70167951 0.07708073]]
After Normalization
[[0.95657697 0.843088   0.04866943 0.16380564 0.        ]
 [0.64583251 1.         0.15889731 0.43174572 0.5715944 ]
 [0.93140354 0.44286086 0.38456045 0.32574332 0.54832925]
 [0.97285547 0.98044006 0.61268832 0.64927457 0.92018048]
 [0.39857543 0.51380403 0.10587563 0.76471461 0.06739303]]


# 5.  How to find common values between two arrays?

In [14]:
a = np.array([0, 45, 55, 65, 75])
print("Array A: ",a)
b = [12, 45, 35, 75]
print("Array B: ",b)
print("Common values between two arrays:")
print(np.intersect1d(a, b))

Array A:  [ 0 45 55 65 75]
Array B:  [12, 45, 35, 75]
Common values between two arrays:
[45 75]


# 6.How to get the dates of yesterday, today and tomorrow?

In [17]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [21]:
x = np.random.randint(0,3,4)
print("First array:")
print(x)
y = np.random.randint(0,3,4)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 0 2 1]
Second array:
[0 1 0 2]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [23]:
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.91094478 0.43029868 0.96528525 0.42999281 0.83045729 0.74535682
 0.42715807 0.42898141 0.58188854 0.59834839]
Maximum value replaced by 0:
[0.91094478 0.43029868 0.         0.42999281 0.83045729 0.74535682
 0.42715807 0.42898141 0.58188854 0.59834839]


# 9. How to print all the values of an array?

In [24]:
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [25]:
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.36565529 0.40530559 0.80245104 0.55497925 0.79762008 0.30793209
  0.14883747 0.35986789 0.47965852 0.12869336]
 [0.33055053 0.67224555 0.1853601  0.94682331 0.11211638 0.46338627
  0.85481277 0.48810803 0.48548545 0.58706113]
 [0.59507012 0.68998645 0.34139022 0.22991572 0.29163867 0.01771913
  0.8233652  0.018141   0.24133318 0.56952404]
 [0.32065967 0.91095086 0.89804659 0.49864377 0.21580499 0.39062206
  0.4737303  0.98883926 0.01712954 0.16455476]
 [0.5536117  0.46120207 0.49326635 0.86514172 0.1985829  0.08318694
  0.0558533  0.66048619 0.95499227 0.92560392]]

Subtract the mean of each row of the said matrix:

[[-0.06944477 -0.02979447  0.36735098  0.11987919  0.36252002 -0.12716797
  -0.28626258 -0.07523217  0.04455846 -0.3064067 ]
 [-0.18204442  0.1596506  -0.32723485  0.43422836 -0.40047857 -0.04920868
   0.34221782 -0.02448693 -0.0271095   0.07446618]
 [ 0.21326175  0.30817807 -0.04041816 -0.15189265 -0.09016971 -0.36408924
   0.44155683 -0.36366737 -0.1

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [38]:
a = np.array([1, 2, 3, 4])
np.add.at(a, [0, 1, 2, 2], 1)

In [39]:
a

array([2, 3, 5, 4])

# 12.How to get the diagonal of a dot product?

In [29]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
print("DOT product is ::: ")
dt=np.dot(a,b)
print(dt)
print("DIAGNOL OF DOT product is ::: ")
np.diag(dt)

DOT product is ::: 
[[37 40]
 [85 92]]
DIAGNOL OF DOT product is ::: 


array([37, 92])

# 13.How to find the most frequent value in an array?

In [31]:
a = np.array([0, 45, 55, 65, 75 ,65 ,34, 65])
print(np.bincount(a).argmax())

65


# 14.How to get the n largest values of an array

In [34]:
a = np.array([0, 45, 55, 65, 75 ,85 ,34, 35])
n = int(input())
print (a[np.argsort(a)[-n:]])

3
[65 75 85]


# 15.How to create a record array from a regular array?

In [3]:
a1=np.array([1,2,3,4])
a2=np.array(['A','B','C','D'])
a3=np.array([12.20,15,20,40])


In [4]:
np.core.records.fromarrays([a1, a2, a3],names='a,b,c')

rec.array([(1, 'A', 12.2), (2, 'B', 15. ), (3, 'C', 20. ), (4, 'D', 40. )],
          dtype=[('a', '<i4'), ('b', '<U1'), ('c', '<f8')])